; ==========================================================================
; SARL B.A. LAB — PlatformIO Project Configuration
; Board: ESP32 DevKitC v4
; ==========================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    sensirion/SensirionI2CScd4x @ ^0.4.0
    Wire
